```{r pred, cache=cacheon}


  mod <- coxph(formula(paste0("Surv(sos_outtime_death, sos_deathcause_cat2 =='", val, "') ~ shf_ef_cat")),
    data = rsdata
  )
  smod <- summary(mod)

  
ormod <- with(imp, lme4::glmer(formula(paste0("num_dmRCT == 'Yes' ~ ", paste(modvars, collapse = " + "), " + (1 | num_nation)")),
  family = "binomial"
))

sormod <- summary(pool(ormod))

nval <- length(sormod$term)
orforest <- data.frame(
  var = as.character(sormod$term[2:nval]),
  logor = sormod$estimate[2:nval],
  lci = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
  uci = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
  p = fn(sormod$p.value[2:nval], dig = 3, p = TRUE)
) %>%
  mutate(orp = paste0(fn(exp(logor), 2), " (", fn(exp(lci), 2), "-", fn(exp(uci), 2), "), ", p)) %>%
  # remove = Yes
  mutate(Variable = str_replace(var, fixed("Yes"), ""))

orforest <- orforest %>%
  mutate(
    modnameforest = case_when(
      Variable == "num_dmPtypeInpatient" ~ "Inpatient vs Outpatient",
      Variable == "num_age_cat>=65" ~ "Age \u226565 years",
      Variable == "num_dmgenderFemale" ~ "Female Sex",
      Variable == "num_dmBmi_cat>=25" ~ "BMI \u226525 kg/m2",
      Variable == "num_dmhome_catHome with family(partner)" ~ "Home with family vs Other",
      Variable == "num_dmhome_catHome alone" ~ "Home alone vs Other",
      Variable == "num_dmBp1_cat>=100" ~ "Systolic BP \u2265100 (mmHg)",
      Variable == "num_dmBpm_cat>=70" ~ "Heart rate \u226570 (beats/min)",
      Variable == "per_congestion" ~ "Peripheral congestion",
      Variable == "pulm_congestion" ~ "Pulmonary congestion",
      Variable == "num_Hypop" ~ "Peripheral hypoperfusion",
      Variable == "d_HFdiagnosis>12mo" ~ "HF History >12 vs <12 (months)",
      Variable == "num_dmEtio_c1Ischemic heart disease" ~ "Ischaemic aetiology",
      Variable == "num_dmSmoking_catCurrent" ~ "Current smoker",
      Variable == "num_dmDiab_c1" ~ "Diabetes",
      Variable == "num_dmCopd" ~ "COPD",
      Variable == "num_dmApn" ~ "Sleep apnea",
      Variable == "num_dmStroke" ~ "Prior stroke/TIA",
      Variable == "num_dmHyChol" ~ "Hypercholesterolaemia",
      Variable == "num_dmHepa" ~ "Hepatic dysfunction",
      Variable == "num_dmDepr" ~ "Depression",
      Variable == "num_dmAfib_c1" ~ "Atrial Fibrillation/Flutter",
      Variable == "num_dmHT" ~ "Hypertension",
      Variable == "num_dmMi" ~ "Previous myocardial infarction",
      Variable == "num_dmPci" ~ "Previous PCI",
      Variable == "num_dmCabg" ~ "Previous CABG",
      Variable == "num_dmValve" ~ "Previous valve surgery",
      Variable == "num_dmPvd" ~ "Peripheral vascular disease",
      Variable == "num_dmVte" ~ "Previous venous thromboembolism",
      Variable == "num_dmDis" ~ "Current malignancy",
      Variable == "num_Nyha_catIII-IV" ~ "NYHA class III-IV vs I-II",
      Variable == "num_Ef_cat41-49%" ~ "LVEF 41-49% vs \u226440 (%)",
      Variable == "num_Ef_cat>=50%" ~ "LVEF \u226550 vs \u226440 (%)",
      Variable == "num_MitReg" ~ "Mitral regurgitation moderate-severe",
      Variable == "num_Nt_cat>=1000" ~ "NT-pro-BNP >1000 (pg/mL)",
      Variable == "num_CKDEPI_cat<60" ~ "eGFR <60 (mL/min/1.73m2)",
      TRUE ~ Variable
    )
  )
```


```{r predplot, fig.cap="Associations with trial participation", cache=cacheon, dependson="pred"}

# exp(min(orforest$lci))
# exp(max(orforest$uci))

orforest <- orforest %>%
  arrange(desc(logor)) %>%
  mutate(order = 1:n())

cextext <- 0.85
minmy <- 0.4
maxmy <- 2

# c(bottom, left, top, right)
par(mar = c(4, 20, 0, 0.5) + 0.2)
plot(orforest$logor, orforest$order,
  xlab = "",
  xlim = c(
    log(minmy),
    log(maxmy)
  ),
  ylim = c(1, max(orforest$order)),
  axes = FALSE,
  ylab = NA,
  cex.lab = 1.1,
  main = NA,
  cex = 1.75,
  type = "p",
  pch = 22,
  bg = global_cols[3],
  col = global_cols[3],
  xaxs = "i"
)


for (i in 1:nrow(orforest)) {
  matplot(c(orforest$lci[i], orforest$uci[i]), c(orforest$order[i], orforest$order[i]),
    type = "l", add = TRUE, col = global_cols[3], lwd = 2
  )
  # if lci < minmy
  if (orforest$lci[i] < log(minmy)) {
    arrows(log(minmy) + 0.01, orforest$order[i], log(minmy),
      orforest$order[i],
      col = global_cols[3],
      code = 2, length = 0.095, lwd = 2
    )
  }
  # if uci > maxmy
  if (orforest$uci[i] > log(maxmy)) {
    arrows(log(maxmy) - 0.01, orforest$order[i], log(maxmy),
      orforest$order[i],
      col = global_cols[3],
      code = 2, length = 0.095, lwd = 2
    )
  }
}

matplot(c(0, 0), c(-1, nrow(orforest) + 0.5), type = "l", lty = 3, add = TRUE, col = "black")

axis(1,
  cex.axis = cextext, at = log(c(minmy, 1, maxmy)),
  labels = c(minmy, 1, maxmy)
)

axis(2,
  at = 1:nrow(orforest),
  labels = orforest$modnameforest,
  cex.axis = cextext, tick = FALSE, las = 2, line = 19, hadj = 0
)

axis(2,
  at = nrow(orforest) + 1,
  labels = "OR (95% CI), p-value",
  cex.axis = cextext, tick = FALSE, las = 2, line = 3.5, hadj = 0.5, font = 2
)
axis(2,
  at = 1:nrow(orforest),
  labels = orforest$orp,
  cex.axis = cextext, tick = FALSE, las = 2, line = 3.5, hadj = 0.5
)

axis(1,
  at = 0, cex.axis = cextext,
  labels = "OR (95% CI)", line = 1, tick = FALSE
)
axis(1,
  at = 0, cex.axis = cextext,
  labels = "Less        RCT        More", line = 2, tick = FALSE
)
```
